version: '3'

networks:
  logging:

services:
  app:
    image: beka13/python_app:latest
    container_name: logging_monitoring
    ports:
      - "3030:80"
    networks:
      - logging
    logging:
      driver: "json-file"
      options:
        tag: "{{ .ImageName }}|{{ .Name }}"

  loki:
    image: grafana/loki:2.3.0
    container_name: logging_loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - ./loki.yml:/etc/loki/loki.yml
    networks:
      - logging
    mem_limit: "256m"

  promtail:
    image: grafana/promtail:2.3.0
    container_name: logging_promtail
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml
    networks:
      - logging
    mem_limit: "256m"

  grafana:
    image: grafana/grafana:8.1.3
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - logging
    mem_limit: "256m"

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    ports:
      - 9090:9090
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - logging
    mem_limit: "256m"
