pipeline {

    environment {
        PDM_VERSION = '1.8.0'
        APP_PATH = 'app_python'
        CODE = 'app.py'
        TESTS = 'test'
        IMAGE_NAME = 'python_app'
        DOCKERHUB_USERNAME = 'beka13'
    }
    agent { 
        dockerfile { 
            dir 'jenkins'
            args '-u root -v $HOME/.cache:/root/.cache -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('deps') {
            steps {
                dir("${APP_PATH}") {
                    sh 'pdm install'
                }
            }
        }
        stage('lint-test') {
            steps {
                parallel (
                    'codestyle': {
                        dir("${APP_PATH}") {
                            sh 'pdm run isort ${CODE}'
                            sh 'pdm run black ${CODE}'
                        }
                    },
                    'lint': {
                        dir("${APP_PATH}") {
                            sh 'pdm run pylint ${CODE}'
                        }
                    }, 
                    'test': {
                        dir("${APP_PATH}") {
                            sh 'pdm run python -m pytest ${TESTS}'
                        }
                    }
                )
                
            }
        }
        stage('Build and Deploy') {
            steps {
                dir("${APP_PATH}") {
                    script {
                        def image = docker.build('$DOCKERHUB_USERNAME/$IMAGE_NAME:latest')
                        docker.withRegistry('', 'dockerhub') {
                            image.push()
                        }
                    }
                }
            }
        }  
    }
    post {
        cleanup { cleanWs() }
    }
}
