apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    app: app
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
type: Opaque
data:
  key: {{ .Values.secrets.key | b64enc | quote }}