# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: app_python

on:
  push:
    branches: [master]

env:
  APP_PATH: ./app_python  # source root
  TESTS: test  # package with tests (inside source root)
  IMAGE_NAME: beka13/python_app  # name for Docker image


jobs:
  lint_test:  # Run linters and test application
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.APP_PATH }}
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        tox-version: ["==3.17", "==3.18.0", "==3.19.0", "==3.20.0", ""]
  
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install tox${{ matrix.tox-version }} tox-gh-actions pdm .
    
    - name: Run linters
      run: |
        pdm run pylint --rcfile=.pylintrc ${{ env.CODE }}
    
    - name: Run tests
      run: |
        pdm run python -m pytest --cov=app ${{ env.TESTS }}
      
    
    
    
    
    
    
    
